module.exports.DEVICE_NOT_CONN = 0x1;
module.exports.UNEXPECTED_MESSAGE_TYPE = 0x2;
module.exports.PROVISIONEDNODE_NULL = 0x3;//
module.exports.STATE_ALREADY_SCANNING = 0x04;//已经在扫描
module.exports.NOT_VALIABLE_MESH_SERVICES = 0x05;//未发现mesh 服务
module.exports.NOT_INIT_LISTENER = 0x06;//未初始化监听器
module.exports.MESH_CONFIG_PROVIDER_NULL=0x07//mesh config data provider can not be null
module.exports.CONFIG_FILED_NULL=0x08//config 字段不存在
module.exports.NOT_INIT = 10000;//未初始化蓝牙适配器
module.exports.NOT_AVAILABLE = 10001;//当前蓝牙适配器不可用
module.exports.NO_DEVICE = 10002;//没有找到指定设备
module.exports.CONNECTION_FAIL = 10003;//连接失败
module.exports.NO_SERVICE = 10004;//没有找到指定服务
module.exports.NO_CHARACTERISTIC = 10005;//没有找到指定特征值
module.exports.NO_CONNECTION = 10006;//当前连接已断开
module.exports.PROPERTY_NOT_SUPPORT=10007;//当前特征值不支持此操作
module.exports.SYSTEM_ERROR = 10008;//其余所有系统上报的异常
module.exports.SYSTEM_NOT_SUPPORT = 10009;//Android 系统特有，系统版本低于 4.3 不支持 BLE
module.exports.OPERATE_TIME_OUT = 10012;//连接超时
module.exports.INVALIDE_DATA = 10013;//连接 deviceId 为空或者是格式不正确
